### ISSUE TITLE
Question 41

### ISSUE THREAD

**Issue by freddyflo** [StenlyTU/K8s-training-official#8]
Hi,

Thanks for providing these questions to help with the preparation for CKA exams.

I noticed namespace is being provided for the creation of clusterrole and clusterrole binding resources in question 41. I believe since these are cluster scoped resources, it will not be necessary to provide the namespace.

**Comment by Warns** [comment]
@freddyflo but for example this won't work `kubectl -n practice create clusterrolebinding pvviewer-role-binding-practice --clusterrole=pvviewer-role-practice --serviceaccount=practice:pvviewer-practice` if you don't provide the namespace when declaring the `--serviceaccount=`

**Comment by StenlyTU** [comment]
Hi all
Recently there was PR for that: https://github.com/StenlyTU/K8s-training-official/pull/7
Will check it, 10x for the interest.

**Comment by StenlyTU** [comment]
@Warns is right, so closing it.

**Comment by freddyflo** [comment]
> @freddyflo but for example this won't work `kubectl -n practice create clusterrolebinding pvviewer-role-binding-practice --clusterrole=pvviewer-role-practice --serviceaccount=practice:pvviewer-practice` if you don't provide the namespace when declaring the `--serviceaccount=`

@StenlyTU @Warns I was referring to the **kubectl -n practice**. namespace is definitely required for serviceaccount

**Comment by StenlyTU** [comment]
@freddyflo Please create PR for that
